rootProject.buildFileName = "build.gradle.kts"
rootProject.name = "CookiGo"
include(":app")
include(":app:base")
include(":app:base:common")
include(":app:base:arch")
include(":app:base:data")
include(":app:base:data:api")
include(":app:base:domain")
include(":app:features")
include(":app:features:auth")
include(":app:features:preferences")
include(":app:features:main")
include(":app:features:home")
include(":app:features:account")
include(":app:features:recipe")
include(":app:features:favourites")
include(":app:features:checklist")
include(":app:features:search")
